- name: Testing Handlers
  hosts: all
  force_handlers: true
  tasks:
  - block:
    - name: Install Dotnet4.6.1
      win_chocolatey:
        name: flashplayerpp
        state: present
    rescue:
    - name: Install Dotnet4.6.1
      win_chocolatey:
        name: flashplayerppapi
        state: absent
    always:
    - name: This is Nazirah
      debug:
        msg: hahahahaa lalalalla
  - name: This is a task
    debug:
      msg: hello world