- name: Testing Handlers
  hosts: all
  tasks:
  - name: Install VLC
    win_chocolatey:
      name: vlc
      state: present
    notify:
    - reboot server
  - name: failing the task
    debug:
      msg: failing the task as testing requires
    failed_when: true
    ignore_errors: true
  - name: This is another task
    debug:
      final task
  handlers:
  - name: reboot server 
    win_reboot: